In [5]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA version:", torch.version.cuda)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))
    print("GPU capabilities: ", torch.cuda.get_arch_list())

PyTorch version: 2.5.1
CUDA version: 11.8
GPU available: True
GPU Name: NVIDIA GeForce GTX 1650 SUPER
GPU capabilities:  ['sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_90', 'sm_37', 'compute_37']


In [23]:
import torch

#Introduction to tensors
#scalars
scalar = torch.tensor(7)
scalar
scalar.item()


#vectors
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

#matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix
matrix.ndim
matrix.shape

#tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor
tensor.ndim
tensor.shape

torch.Size([1, 3, 3])

In [29]:
### Random tensors
random_tensor = torch.rand(3,4)
random_tensor

random_tensor.ndim

# create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [87]:
### 1. Zeros and ones
zeros = torch.zeros(size=(3,4))
zeros

ones = torch.ones(size=(3,4))
ones

ones.dtype


## Create a range of tensors
one_to_ten = torch.arange(1,11)
one_to_ten

one_to_ten_two_steps = torch.arange(start=1,end=11,step=2)
one_to_ten_two_steps

## creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

## 2. Tensor datatypes
# *note*: Tensor datatypes is one of the 3 big error sources you'll run into with PyTorch & deep learning:
# i. Tensors not right datatype
# ii. Tensors not right shape
# iii. Tensors not on the right device
float32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # what datatype is the tensor (torch.tensor has data types)
                              device=None,
                              requires_grad=False)
float32_tensor

#float16_tensor = float32_tensor.type(torch.float16)
int32_tensor = torch.tensor([3,6,9],
                           dtype=torch.int32)

int32_tensor * float32_tensor


## 3. Tensor Attributes
#. datatype - tensor.dtype
#. shape - tensor.shape
#. device - tensor.device

some_tensor = torch.tensor([3,4])
some_tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")


## 4. Manipulating Tensors (Tensor operations)
# Tensor operations include: addition, subtraction etc.

t1 = torch.tensor([1,2,3])
t1 + 10
t1 * 10
t1 - 10

# PyTorch in-built functions: .mul, .add, etc
#torch.mul(t1,10)

# Element-wise & Matrix multiplication
print(t1, '*', t1)
print(f"Equals: {t1 * t1}")

print(torch.matmul(t1,t1)) # equivalent to t1 @ t1

## Matrix multiplication rules:
# i. inner dimensions must match e.g: (3,2) @ (2,3) is fine as inner-dims are of size 2, but (3, 2) @ (3, 2) won't work
# ii. resulting matrix has shape of outer dimensions. i.e. (2, 3) @ (3, 2) produces a (2, 2) sized matrix

## Shapes for matrix multiplication
tA = torch.tensor([[1,2],
                   [3,4],
                   [5,6]])
tB = torch.tensor([[7,10],
                   [8,11],
                   [9,12]])
tA.shape, tB.shape

# We can manipulate a tensor using a **transpose**
tB = tB.T
torch.mm(tA, tB) # torch.mm is an alias for torch.matmul

Datatype of tensor: torch.int64
Shape of tensor: torch.Size([2])
Device of tensor: cpu
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
tensor(14)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [135]:
## Tensor aggregation: finding the min,max,mean,sum of tensor values
x = torch.arange(0,100,10)
x
torch.min(x), x.min()
torch.max(x), x.max()
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # torch.mean requires a float32 datatype to work

torch.sum(x), x.sum()

# Get minimum value index position: argmin(), argmax()
x.argmax()

## Reshaping, stacking, squeezing and unsqueezing tensors
# Reshaping - reshapes an input tensor to a defined shape
# View - return a view of an input tensor of certain shape but keep the same memory
# Stacking - combine multiple tensors on top of each other
# Squeeze - removes all '1' dimensions from a tensor
# Unsqueeze - add a '1' dimension to a target tensor
# Permute = return a view of the input with dimensions permuted(swapped) in a certain way
y = torch.arange(1.,10.)
y, y.shape

# Add an extra dimension
y_reshaped = y.reshape(1,9)
y_reshaped, y_reshaped.shape

# change the view - changing the view, z below, also changes the source, x, bc a view of a tensor shares the same memory as the original tensor
z = y.view(1,9)
z[:,0] = 5
y
z, z.shape 

# stack tensors on top of each other (default is with a dim = 1), there's also vstack and hstack to look into
y_stacked = torch.stack([x,x,x])
y_stacked

# Squeezing & Unsqueezing
# torch.squeeze removes all single dimensions. for y_reshaped, it changes it's shape from 1,9 -> 9
y_reshaped.squeeze()

# torch.permute - rearranges dimensions as desired e.g torch.permute(x,(2,0,1)) moves 2nd dim to 0, 0 -> 1 and 1 -> 2
# p.s. permute returns a view i.e. it refers to the same original data location
x_og = torch.rand(size=(224,224,2)) # [height, weight, color_channels]

# permute original, x_og, tensor to rearrange the axis (or dim) order
x_permuted = x_og.permute(2,0,1)
print(f"Previous shape: {x_og.shape}")
print(f"New shape: {x_permuted.shape}")

## (Indexing) Select data from tensors
r = torch.arange(1,10).reshape(1,3,3)
r, r.shape

# the semicolon, :, is used to select "ALL" for a target dimension
print(r)
r[:, 2]
#r[:, :, 2]
#r[0, 0, :]
r[:,2,2]

Previous shape: torch.Size([224, 224, 2])
New shape: torch.Size([2, 224, 224])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


tensor([9])

In [143]:
# PyTorch tensors & NumPy (python numerical computing library)
# demonstrate numpy array to tensor
import torch
import numpy as np

arr = np.arange(1.0,8.0)
tensr = torch.from_numpy(arr) # Note: when converting numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless otherwise specified
arr, tensr

# change the value of array (does NOT update tensor and vice-versa. i.e. they do NOT share memory)
arr = arr + 1
arr, tensr

# Go from tensor to numpy
tensr2 = torch.ones(7)
numpy_tensr = tensor.numpy()
tensr2, numpy_tensr

#numpy_tensr.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]]))

In [152]:
# Reproducibility
# in short, how a neural network learns:
# start with random numbers -> tensor operations -> update random nums to try and make them better representations of the data -> repeat -> repeat...

# to reduce the randomness in neural networks, we use the random seed
import torch
rand_seed = 42

torch.manual_seed(rand_seed)
rand_tens_A = torch.rand(3,4)

torch.manual_seed(rand_seed)
rand_tens_B = torch.rand(3,4)

print(rand_tens_A) 
print(rand_tens_B)

print(rand_tens_A == rand_tens_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [13]:
## Running tensors/pytorch objects on GPUs and making faster computations
#!nvidia-smi
import torch

# Setup device-agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
#device

torch.cuda.device_count()

# Putting tensors (and models) on the GPU
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
#print(tensor, tensor.device)

# Move Tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# Moving tensor back to CPU (to use things like numpy, which cannot be used on GPU)
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy() # or tensor_on_gpu.to('cpu')
tensor_back_to_cpu

array([1, 2, 3])

In [14]:
# Exercises
#00 learnpytorch.io/00_pytorch_fundamentals
# do fundamentals exercise